---
- name: FAIL2BAN | Install fail2ban
  apt:
    name: ['fail2ban']
    state: present
    update_cache: yes
    cache_valid_time: 3600

# ssh
- name: FAIL2BAN | Activate ssh jails
  copy:
    src: etc/fail2ban/jail.d/ssh.conf
    dest: /etc/fail2ban/jail.d/ssh.conf

# webdav-401
# TODO -> Move to WebDAV
- name: FAIL2BAN | Deploy jail webdav-401
  when: fail2ban_jail_webdav
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'etc/fail2ban/filter.d/webdav-401.conf', dest: '/etc/fail2ban/filter.d/webdav-401.conf' }
    - { src: 'etc/fail2ban/jail.d/webdav-401.conf', dest: '/etc/fail2ban/jail.d/webdav-401.conf' }

# Default jails parameters
- name: FAIL2BAN | Deploy configuration
  template:
    src: etc/fail2ban/jail.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
