---
- name: FAIL2BAN | Install fail2ban
  apt:
    name: ['fail2ban', 'python-pyinotify', 'gamin', 'python3-systemd']
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Get deb
  get_url:
    # url: https://github.com/fail2ban/fail2ban/releases/download/0.10.6/fail2ban_0.10.6-1.upstream1_all.deb
    url: "{{ fail2ban_deb_url }}"
    force: yes
    dest: /tmp/fail2ban.deb

- name: Get asc
  get_url:
    url: "{{ fail2ban_deb_url }}.asc"
    force: yes
    dest: /tmp/fail2ban.deb.asc

# Get fail2ban key: gpg --keyserver keys.gnupg.net --recv-keys BD0A882C
# Check signature: gpg --verify fail2ban_0.10.6-1~upstream1_all.deb.asc fail2ban_0.10.6-1~upstream1_all.deb
-
- name: Install fail2ban
  apt: deb="/tmp/fail2ban.deb"
