---
# ssh
- name: FAIL2BAN | Activate ssh jails
  when: fail2ban_activate_ssh_jail
  template:
    src: etc/fail2ban/jail.d/ssh.conf.j2
    dest: /etc/fail2ban/jail.d/ssh.conf
  notify: restart fail2ban
