---
- name: Gather package facts
  package_facts:
    manager: auto
- name: INCLUDE | Install fail2ban
  import_tasks: install.yml
  when: "'fail2ban' not in ansible_facts.packages"

- name: INCLUDE | Configure fail2ban
  import_tasks: configure.yml

- name: INCLUDE | Configure jails
  import_tasks: jails.yml
